# NumPy

Load the NumPy (Numerical Python) package.

https://numpy.org/doc/stable/user/absolute_beginners.html


In [5]:
import numpy as np

Differently from Python, NumPy arrays (ndarray) are homogeneous (same type data), with a fixed size at creation and "n" numbers of dimensions.

NumPy can execute operations on large amounts of data (advanced math operations) more efficiently than Python's built in functions. 

In [ ]:
# create a 2D array
a = np.array ([[1,2,3],
               [4,5,6]])
# show the shape of the array
a.shape
#show the array
print(a)

In [ ]:
b = np.array ([[7, 8, 9],
               [10, 11, 12]])
print(b)

If we add an element (float) different from the rest of the elements (int), everything will be stored/converted to the new element type (float).


In [29]:
f = np.array ([[7, 8.0, 9],
               [10, 11, 12]])
print(f)

[[ 7.  8.  9.]
 [10. 11. 12.]]


Creating a 2D array is like creating lists inside of another list.

[

    [],

    [],

    [],

]


Arrays can be multi-dimensional. When we have > 2 dimensions, and create lists inside of other lists, inside of other lists.

Multidimensional arrays can be difficult to visualize.

In [ ]:
# creation of a 3D array
m = np.array(
    [
        [
            [1, 2], [3, 4], [5, 6],
        ],
        [
            [7, 8], [9, 10], [11, 12]
        ],
        [
            [13, 14], [15, 16], [17, 18]
        ],
    ]
        )
print(m)

The number of elements (columns) contained in each dimension (row) should be the same, while the number of rows has no constraints. The array should have a "rectangular" shape.



## Indexing (accessing elements)

In [37]:
print(m)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [ ]:
# accessing elements of the array M
# access the first list
print(m[0])


[[1 2]
 [3 4]
 [5 6]]


In [39]:
# access the first list in the first list
print(m[0][0])


[1 2]


In [40]:
# access the first element in the first list in the first list
print(m[0][0][0])

1


In [42]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# access the second element of the first row of A
print(a[0][1])    # number of row [0] number of column [1]

2


In [43]:
# NumPy allows us to use commas, instead of writing many [] (differently from Python)
# alternative method to access the second element of the first row of A:
print(a[0, 1])

2


In [44]:
# access the first element of the second row
print(a[1, 0])

4


In [45]:
# access the entire first row 
print(a[0])

[1 2 3]


Access columns

In [ ]:
# access the entire first column
print(a[:,0])          # ":" means "everything in this dimension"

[1 4]


Slicing

In [ ]:
p = np.arange (20)   
print (p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
x = np.arange (3, 21, 2)        # .arange (start, stop, step)
print (x)

[ 3  5  7  9 11 13 15 17 19]


In [ ]:
# access the first 5 elements
print (p [:5])

[0 1 2 3 4]


In [ ]:
# access the next 5 elements
print (p [5: 10])

[5 6 7 8 9]


In [ ]:
# access every second element
print (p [0 : len(p) : 2])

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# same thing as above
print (p [::2])

[ 0  2  4  6  8 10 12 14 16 18]


## Analyze Arrays Properties

We can use methods to analyze arrays, visualize how many dimensions they have, how many columns and rows, etc.

In [ ]:
# show number of rows and columns
m.shape
# see the number of dimensions
print(m.ndim)
# see the type of the elements
print(m.dtype)


## Operations on Arrays

Addition

In [ ]:
# add a constant to an array: adds the constant to each element
a + 4


array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
# add 2 arrays: adds the corresponding elements of the 2 arrays
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

Multiplication

In [ ]:
# add 2 arrays when number of elements is different:
c = np.array ([[9, 5, 6, 8],
               [4, 3, 7, 6]])
c + a
# we get an error!

In [16]:
# multiply an array for a constant
b * 8

array([[56, 64, 72],
       [80, 88, 96]])

In [17]:
# multiply 2 arrays
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
# matrix multiplication (multiplies first row of A by the first columnn of D, etc.).
# In matrix multiplications the number of elements contained in the row of A should be equal to the number of elements contained in the corresponding column of B.
# we can't multiply A @ B because A has 3 elements in its rows and B has 2 elements in its columns.
d = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8 ,9]])
a @ d

array([[30, 36, 42],
       [66, 81, 96]])

## END